# Generated by Django 4.2.11 on 2024-05-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecordedVideo',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('video_is_public', models.BooleanField(default=True)),
                ('thumbnail', models.CharField(max_length=225)),
                ('videoname', models.CharField(max_length=64)),
                ('videoplay', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'recorded_video',
                'managed': False,
            },
        ),
    ]
