import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from 'next/font/local';
import NavBar from "@/components/NavBar";
import * as styles from './layout.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ving",
  description: "Generated by create next app",
};

const pretendard = localFont({
  src: "../../public/fonts/Pretendard-Regular.woff",
  display: "swap",
  weight: "45 920",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr">
      <body className={pretendard.className}>
        <NavBar />
        <div className={styles.container}>
          {children}
        </div>
        </body>
    </html>
  );
}
