# Generated by Django 4.2.11 on 2024-05-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_id', models.AutoField(primary_key=True, serialize=False)),
                ('notice_content', models.CharField(choices=[('streaming', 'Streaming'), ('recording', 'Recording')], default='streaming', max_length=10)),
            ],
            options={
                'db_table': 'notice',
                'managed': False,
            },
        ),
    ]
